version: '3.9'
services:
  kafka-ui:
    container_name: kafka-ui
    image: docker.redpanda.com/vectorized/console:latest
    ports:
      - 8089:8080
    environment:
      - KAFKA_BROKERS=glider-02.srvs.cloudkafka.com:9094,glider-03.srvs.cloudkafka.com:9094,glider-01.srvs.cloudkafka.com:9094
      - KAFKA_TLS_ENABLED=true
      - KAFKA_SASL_ENABLED=true
      - KAFKA_SASL_MECHANISM=SCRAM-SHA-512
      - KAFKA_SASL_USERNAME=7dmi9iq4
      - KAFKA_SASL_PASSWORD=aXX_H0zHZppzr995NzZLULPXuz4KNA2q
