version: '3.9'
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:7.1.2
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: 192.168.13.181:22888:23888;192.168.13.181:32888:33888;192.168.13.181:42888:43888
    network_mode: host

  zookeeper-2:
    image: confluentinc/cp-zookeeper:7.1.2
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: 192.168.13.181:22888:23888;192.168.13.181:32888:33888;192.168.13.181:42888:43888
    network_mode: host
   
  zookeeper-3:
    image: confluentinc/cp-zookeeper:7.1.2
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 42181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: 192.168.13.181:22888:23888;192.168.13.181:32888:33888;192.168.13.181:42888:43888
    network_mode: host
   

  kafka-1:
    image: confluentinc/cp-kafka:7.1.2
    network_mode: host
    ports:
      - "19092:19092"
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 192.168.13.181:22181,192.168.13.181:32181,192.168.13.181:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.13.181:19092
   

  kafka-2:
    image: confluentinc/cp-kafka:7.1.2
    network_mode: host
    ports:
      - "29092:29092"
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 192.168.13.181:22181,192.168.13.181:32181,192.168.13.181:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.13.181:29092
   

  kafka-3:
    image: confluentinc/cp-kafka:7.1.2
    network_mode: host
    ports:
      - "39092:39092"
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: 192.168.13.181:22181,192.168.13.181:32181,192.168.13.181:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.13.181:39092
    

  schema_registry:
    image: confluentinc/cp-schema-registry:7.1.2
    hostname: schema_registry
    ports:
      - 8082:8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema_registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: '192.168.13.181:22181,192.168.13.181:32181,192.168.13.181:42181'
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'PLAINTEXT://192.168.13.181:19092,PLAINTEXT://192.168.13.181:29092,PLAINTEXT://192.168.13.181:39092'

  kafka-redpanda-ui:
    container_name: kafka-redpanda-ui
    image: docker.redpanda.com/vectorized/console:latest
    depends_on: 
        - kafka-1
        - kafka-2
        - kafka-3
    ports:
      - 8089:8080
    environment:
      - KAFKA_BROKERS=192.168.13.181:19092,192.168.13.181:29092,192.168.13.181:39092